server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kiranastore_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

currency:
  rates:
    api: https://api.fxratesapi.com/latest
